name: fresean-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.28.0=py312hecd8cb5_0
  - ipython=8.25.0=py312hecd8cb5_0
  - ipywidgets=8.1.2=py312hecd8cb5_0
  - jupyter=1.0.0=py312hecd8cb5_9
  - matplotlib=3.9.2=py312hecd8cb5_0
  - numpy=1.26.4=py312h7d6adbd_0
  - pip=25.1.1=pyh8b19718_0
  - pyvista=0.45.2=pyhd8ed1ab_0
  - pip:
      - imdclient==0.1.3
      - mdanalysis==2.7.0
      - pyvista[jupyter]
